### ISSUE TITLE
sbt build with spark 1.6.1 not working

### ISSUE THREAD

**Issue by argaen** [RedisLabs/spark-redis#34]
Hi!

I'm trying to build the package with `sbt package` for spark version 1.6.1 and the following error occurs:

```
16:56 $ sbt package
[info] Loading project definition from /Users/manuelmiranda/Downloads/spark-1.6.1-bin-without-hadoop/lib/spark-redis/project
[info] Set current project to spark-redis (in build file:/Users/manuelmiranda/Downloads/spark-1.6.1-bin-without-hadoop/lib/spark-redis/)
[warn] Credentials file /Users/manuelmiranda/.ivy2/.sbtcredentials does not exist
[info] Compiling 9 Scala sources to /Users/manuelmiranda/Downloads/spark-1.6.1-bin-without-hadoop/lib/spark-redis/target/scala-2.11/classes...
[error] /Users/manuelmiranda/Downloads/spark-1.6.1-bin-without-hadoop/lib/spark-redis/src/main/scala/com/redislabs/provider/redis/sql/DefaultSource.scala:10: object Row is not a member of package org.apache.spark.sql.catalyst.expressions
[error] import org.apache.spark.sql.catalyst.expressions.Row
[error]        ^
[error] /Users/manuelmiranda/Downloads/spark-1.6.1-bin-without-hadoop/lib/spark-redis/src/main/scala/com/redislabs/provider/redis/sql/DefaultSource.scala:53: not found: type Row
[error]         val m: Map[String, Row] = partition.map {
[error]                            ^
[error] /Users/manuelmiranda/Downloads/spark-1.6.1-bin-without-hadoop/lib/spark-redis/src/main/scala/com/redislabs/provider/redis/sql/DefaultSource.scala:78: not found: type Row
[error]   def buildScan(requiredColumns: Array[String], filters: Array[Filter]): RDD[Row] = {
[error]                                                                              ^
[error] /Users/manuelmiranda/Downloads/spark-1.6.1-bin-without-hadoop/lib/spark-redis/src/main/scala/com/redislabs/provider/redis/sql/DefaultSource.scala:113: not found: value Row
[error] Error occurred in an application involving default arguments.
[error]           }.toIterator.map(Row.fromSeq(_))
[error]                            ^
[error] four errors found
[error] (compile:compile) Compilation failed
[error] Total time: 15 s, completed Jun 15, 2016 4:56:33 PM
```

Same happens with version 1.5.2 which is supposed to work according to [this post](https://redislabs.com/blog/connecting-spark-and-redis#.V2FRHuZ96Rs)

If I set the version to 1.4.1 (same set as in pom.xml) it works correctly.

**Comment by sasajib** [comment]
you can exclude spark-redis bundled spark version. In you build.sbt file
`("com.redislabs" % "spark-redis" % "0.3.5").exclude("org.apache.spark", "*")`

**Comment by fe2s** [comment]
The problem is that spark-redis has a **compile** rather than a **provided** dependency on spark. This should be fixed in the next release. For now please use the workaround suggested by @sasajib
