### ISSUE TITLE
Update Redis Version in Spark Package Repo

### ISSUE THREAD

**Issue by anaqvi2** [RedisLabs/spark-redis#35]
I am using spark 1.6.2 and although I can write to redis, reading does not seem to be working, I am using 0.1.1 as that is the only one available on the spark package repo. Please advise.

sc.toRedisKV(sc.parallelize(("testing", "3") :: Nil), ("localhost", 6379))

127.0.0.1:6379> get "testing"
"3"

 val valuesRDD = sc.fromRedisKV("testing", ("localhost", 6379))
<console>:51: error: value fromRedisKV is not a member of org.apache.spark.SparkContext
         val valuesRDD = sc.fromRedisKV("testing", ("localhost", 6379))

**Comment by shaynativ** [comment]
The following commands worked fine on spark 1.6.2 shell:

```
import org.apache.spark._
import com.redislabs.provider.redis._

sc.getConf.setMaster("local").setAppName("myApp").set("redis.port", "6379") 
sc.toRedisKV(sc.parallelize(("testing", "3") :: Nil), (6379))
val valuesRDD = sc.fromRedisKV("testing", (6379))
valuesRDD.collect

```

Let me know if this helps.

**Comment by anaqvi2** [comment]
Thanks @shaynativ for the reply, which version of redis are you using? I am using 0.1.1 from the spark repo using --packages argument, and get the following error:

./bin/spark-shell --packages RedisLabs:spark-redis:0.1.1

SQL context available as sqlContext.

scala> import org.apache.spark._
import org.apache.spark._

scala> import com.redislabs.provider.redis._
import com.redislabs.provider.redis._

scala> sc.toRedisKV(sc.parallelize(("testing", "3") :: Nil), ("localhost", 6379)) // This works

scala> val valuesRDD = sc.fromRedisKV("testing", (6379))
<console>:33: error: value fromRedisKV is not a member of org.apache.spark.SparkContext
         val valuesRDD = sc.fromRedisKV("testing", (6379))

**Comment by shaynativ** [comment]
Try to config sc like this:
sc.getConf.setMaster("local").setAppName("myApp").set("redis.port", "6379")

**Comment by anaqvi2** [comment]
running your code exactly returns:

SQL context available as sqlContext.

scala> import org.apache.spark._
import org.apache.spark._

scala> import com.redislabs.provider.redis._
import com.redislabs.provider.redis._

scala> 

scala> sc.getConf.setMaster("local").setAppName("myApp").set("redis.port", "6379") 
res0: org.apache.spark.SparkConf = org.apache.spark.SparkConf@231753d8

scala> sc.toRedisKV(sc.parallelize(("testing", "3") :: Nil), (6379))
<console>:34: error: type mismatch;
 found   : Int(6379)
 required: (String, Int)
              sc.toRedisKV(sc.parallelize(("testing", "3") :: Nil), (6379))
                                                                     ^

scala> val valuesRDD = sc.fromRedisKV("testing", (6379))
<console>:33: error: value fromRedisKV is not a member of org.apache.spark.SparkContext
         val valuesRDD = sc.fromRedisKV("testing", (6379))

I changed the write to include localhost and that does work, however I see the same error as above

**Comment by shaynativ** [comment]
Hi, it looks like there is some version mismatch.
Can you try to compile from source?
git clone https://github.com/RedisLabs/spark-redis.git
cd spark-redis
mvn clean package -DskipTests

and then load the jar directly:
./bin/spark-shell --master local[2] --jars <PATH_TO_JAR>/spark-redis-0.1.1-jar-with-dependencies.jar

**Comment by anaqvi2** [comment]
@shaynativ That Worked thanks!

**Comment by anaqvi2** [comment]
@shaynativ Also would you know where I could find some docs to test out the dataframe implementation?

Thanks

**Comment by shaynativ** [comment]
@anaqvi2 Version issue fixed so lading the package works:
spark-shell --packages RedisLabs:spark-redis:0.3.2

There is not yet documentation for the dataframe, but you can see some usage examples in the [SQL test](https://github.com/RedisLabs/spark-redis/blob/master/src/test/scala/com/redislabs/provider/redis/rdd/RedisSparkSQLStandaloneSuite.scala) code.
